# Generated by Django 2.2.12 on 2020-04-24 17:40

from django.db import migrations, models
import helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200424_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text="1) password length is from 8 to 128 letters.2) contains lower case letters.3) contains upper case letters.4) contains numbers.5) contains special characters './!@#$%&;'", max_length=128, validators=[helpers.validators.PasswordValidation], verbose_name='password')),
            ],
        ),
    ]
