# Generated by Django 2.2.12 on 2020-04-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
